// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using P1_AP1_WilliamRodriguez.DAL;

#nullable disable

namespace P1_AP1_WilliamRodriguez.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20251009025001_Segunda")]
    partial class Segunda
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("P1_AP1_WilliamRodriguez.Models.DetalleHuacales", b =>
                {
                    b.Property<int>("DetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EntradaId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Precio")
                        .HasColumnType("TEXT");

                    b.Property<int>("TipoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DetalleId");

                    b.HasIndex("EntradaId");

                    b.ToTable("DetalleHuacales");
                });

            modelBuilder.Entity("P1_AP1_WilliamRodriguez.Models.EntradasHuacales", b =>
                {
                    b.Property<int>("EntradaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreCliente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Precio")
                        .HasColumnType("TEXT");

                    b.HasKey("EntradaId");

                    b.ToTable("Huacales");
                });

            modelBuilder.Entity("P1_AP1_WilliamRodriguez.Models.TipoHuacales", b =>
                {
                    b.Property<int>("TipoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Existencia")
                        .HasColumnType("INTEGER");

                    b.HasKey("TipoId");

                    b.ToTable("TipoHuacales");

                    b.HasData(
                        new
                        {
                            TipoId = 1,
                            Descripcion = "Pequeña Verde",
                            Existencia = 0
                        },
                        new
                        {
                            TipoId = 2,
                            Descripcion = "Pequeña Roja",
                            Existencia = 0
                        },
                        new
                        {
                            TipoId = 3,
                            Descripcion = "Mediana Verde",
                            Existencia = 0
                        },
                        new
                        {
                            TipoId = 4,
                            Descripcion = "Mediana Roja",
                            Existencia = 0
                        },
                        new
                        {
                            TipoId = 5,
                            Descripcion = "Jumbo Verde",
                            Existencia = 0
                        },
                        new
                        {
                            TipoId = 6,
                            Descripcion = "Jumbo Roja",
                            Existencia = 0
                        });
                });

            modelBuilder.Entity("P1_AP1_WilliamRodriguez.Models.DetalleHuacales", b =>
                {
                    b.HasOne("P1_AP1_WilliamRodriguez.Models.EntradasHuacales", null)
                        .WithMany("DetalleHuacales")
                        .HasForeignKey("EntradaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("P1_AP1_WilliamRodriguez.Models.EntradasHuacales", b =>
                {
                    b.Navigation("DetalleHuacales");
                });
#pragma warning restore 612, 618
        }
    }
}
